export type AdminLocale = "ar" | "en";

export const adminLabels = {
  ar: {
    dashboard: {
      title: "لوحة التحكم",
      description: "نظرة عامة على المواعيد والمرضى والفريق",
      totalPatients: "إجمالي المرضى",
      totalDoctors: "إجمالي الأطباء",
      totalAppointments: "إجمالي المواعيد",
      totalDepartments: "إجمالي الأقسام",
      recentPatients: "أحدث المرضى",
      recentAppointments: "أحدث المواعيد",
      appointmentsCalendar: "تقويم المواعيد",
    },
    patients: {
      title: "المرضى",
      description: "جميع المرضى المسجلين",
      newPatient: "مريض جديد",
      search: "ابحث عن مريض...",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      gender: "الجنس",
      appointments: "المواعيد",
      actions: "الإجراءات",
    },
    team: {
      title: "الفريق",
      description: "إدارة فريق العيادة",
      newMember: "عضو جديد",
      permissionGroups: "مجموعات الصلاحيات",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      specialization: "التخصص",
      department: "القسم",
      role: "الدور",
      status: "الحالة",
    },
    departments: {
      title: "الأقسام",
      description: "إدارة أقسام العيادة",
      newDepartment: "قسم جديد",
      name: "الاسم",
      doctors: "الأطباء",
      services: "الخدمات",
      descriptionLabel: "الوصف",
      head: "المسؤول",
    },
    services: {
      title: "الخدمات",
      description: "إدارة خدمات العيادة",
      name: "الاسم",
      department: "القسم",
      price: "السعر",
      duration: "المدة",
    },
    appointments: {
      title: "المواعيد",
      description: "إدارة المواعيد",
      newAppointment: "موعد جديد",
      patient: "المريض",
      date: "التاريخ",
      time: "الوقت",
      status: "الحالة",
      service: "الخدمة",
      employee: "الموظف",
      pending: "قيد الانتظار",
      upcoming: "قادم",
      done: "مكتمل",
      cancelled: "ملغي",
    },
    schedule: {
      title: "الجدول الزمني",
      description: "جداول عمل الأطباء",
      sessionType: "نوع الجلسة",
      period: "الفترة",
    },
    holidays: {
      title: "الإجازات والعطل",
      description: "إدارة الإجازات",
      newHoliday: "إجازة جديدة",
      newLeave: "إجازة موظف",
      reason: "السبب",
      type: "النوع",
    },
    contact: {
      title: "رسائل التواصل",
      description: "الرسائل الواردة",
      new: "جديد",
      read: "مقروء",
      replied: "تم الرد",
      message: "الرسالة",
    },
    evaluations: {
      title: "التقييمات",
      description: "نتائج التقييمات",
      submissions: "الإرسالات",
      score: "النتيجة",
      results: "النتائج",
    },
    blog: {
      title: "المدونة",
      description: "إدارة المقالات",
      newBlog: "مقال جديد",
      creator: "الكاتب",
      category: "التصنيف",
    },
    blogCategories: {
      title: "تصنيفات المدونة",
      description: "إدارة التصنيفات",
      newCategory: "تصنيف جديد",
      blogsCount: "عدد المقالات",
    },
    roles: {
      title: "الأدوار والصلاحيات",
      description: "إدارة الأدوار",
      newRole: "دور جديد",
      members: "الأعضاء",
      permissions: "الصلاحيات",
    },
    accounting: {
      title: "المحاسبة",
      description: "الإيرادات والمصروفات",
      incomes: "الإيرادات",
      expenses: "المصروفات",
      invoiceId: "رقم الفاتورة",
      amount: "المبلغ",
    },
    mail: {
      title: "البريد",
      description: "صندوق الوارد",
      inbox: "الوارد",
      sent: "المرسل",
      newEmail: "رسالة جديدة",
      selectMessage: "اختر رسالة",
    },
    nav: {
      dashboard: "لوحة التحكم",
      ecommerce: "المتجر",
      clinic: "العيادة",
      websiteSetup: "إعدادات الموقع",
    },
    common: {
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      view: "عرض",
      add: "إضافة",
      search: "بحث",
      noData: "لا توجد بيانات",
      loading: "جاري التحميل...",
      confirmDelete: "هل أنت متأكد من الحذف؟",
      savedSuccess: "تم الحفظ بنجاح",
      deletedSuccess: "تم الحذف بنجاح",
      errorOccurred: "حدث خطأ",
      id: "المعرف",
      actions: "الإجراءات",
      fromDatabase: "من قاعدة البيانات",
      language: "English",
      admin: "الإدارة",
    },
  },
  en: {
    dashboard: {
      title: "Clinic Dashboard",
      description: "Appointments, patients, and staff at a glance",
      totalPatients: "Total Patients",
      totalDoctors: "Total Doctors",
      totalAppointments: "Total Appointments",
      totalDepartments: "Total Departments",
      recentPatients: "Recent Patients",
      recentAppointments: "Recent Appointments",
      appointmentsCalendar: "Appointments Calendar",
    },
    patients: {
      title: "Patients",
      description: "All registered patients",
      newPatient: "New Patient",
      search: "Search patients...",
      name: "Name",
      email: "Email",
      phone: "Phone",
      gender: "Gender",
      appointments: "Appointments",
      actions: "Actions",
    },
    team: {
      title: "Team",
      description: "Manage clinic team",
      newMember: "New Member",
      permissionGroups: "Permission groups",
      name: "Name",
      email: "Email",
      phone: "Phone",
      specialization: "Specialization",
      department: "Department",
      role: "Role",
      status: "Status",
    },
    departments: {
      title: "Departments",
      description: "Manage clinic departments",
      newDepartment: "New Department",
      name: "Name",
      doctors: "Doctors",
      services: "Services",
      descriptionLabel: "Description",
      head: "Head",
    },
    services: {
      title: "Services",
      description: "Manage clinic services",
      name: "Name",
      department: "Department",
      price: "Price",
      duration: "Duration",
    },
    appointments: {
      title: "Appointments",
      description: "Manage appointments",
      newAppointment: "New Appointment",
      patient: "Patient",
      date: "Date",
      time: "Time",
      status: "Status",
      service: "Service",
      employee: "Employee",
      pending: "Pending",
      upcoming: "Upcoming",
      done: "Done",
      cancelled: "Cancelled",
    },
    schedule: {
      title: "Schedule",
      description: "Doctors work schedules",
      sessionType: "Session type",
      period: "Period",
    },
    holidays: {
      title: "Holidays & Leaves",
      description: "Manage holidays",
      newHoliday: "New Holiday",
      newLeave: "New Leave",
      reason: "Reason",
      type: "Type",
    },
    contact: {
      title: "Contact Messages",
      description: "Inbound messages",
      new: "New",
      read: "Read",
      replied: "Replied",
      message: "Message",
    },
    evaluations: {
      title: "Evaluations",
      description: "Evaluation results",
      submissions: "Submissions",
      score: "Score",
      results: "Results",
    },
    blog: {
      title: "Blog",
      description: "Manage articles",
      newBlog: "New Blog",
      creator: "Creator",
      category: "Category",
    },
    blogCategories: {
      title: "Blog Categories",
      description: "Manage categories",
      newCategory: "New Category",
      blogsCount: "# of blogs",
    },
    roles: {
      title: "Roles & Permissions",
      description: "Manage roles",
      newRole: "New Role",
      members: "Members",
      permissions: "Permissions",
    },
    accounting: {
      title: "Accounting",
      description: "Incomes and expenses",
      incomes: "Incomes",
      expenses: "Expenses",
      invoiceId: "Invoice ID",
      amount: "Amount",
    },
    mail: {
      title: "Mail",
      description: "Inbox",
      inbox: "Inbox",
      sent: "Sent",
      newEmail: "New Email",
      selectMessage: "Select a message",
    },
    nav: {
      dashboard: "Dashboard",
      ecommerce: "Ecommerce",
      clinic: "Clinic / Medical",
      websiteSetup: "Website Setup",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      view: "View",
      add: "Add",
      search: "Search",
      noData: "No data",
      loading: "Loading...",
      confirmDelete: "Are you sure you want to delete this item?",
      savedSuccess: "Saved successfully",
      deletedSuccess: "Deleted successfully",
      errorOccurred: "Something went wrong",
      id: "ID",
      actions: "Actions",
      fromDatabase: "from database",
      language: "العربية",
      admin: "Admin",
    },
  },
} as const;

export type AdminLabels = (typeof adminLabels)[keyof typeof adminLabels];

export function getAdminLabels(locale: AdminLocale) {
  return adminLabels[locale] ?? adminLabels.ar;
}
